### ISSUE TITLE
mount within volume

### ISSUE THREAD

**Issue by LadySerenaKitty** [xtreemfs/xtreemfs#447]
Hey there!  I'm in the process of building a dev server with Jenkins, svn, (etc...).  There is currently an inability to mount a folder within an xtfs volume.

Our build process is currently assuming a folder within a volume can be mounted.  The idea here is we keep our Jenkins projects inside a single volume and mount/umount them as-needed.  xtfs volume administration would be much easier if we could keep all projects inside a single volume rather than have loads of project volumes.  Pretty sure this could benefit others using xtfs, too. 🐾

**Comment by robert-schmidtke** [comment]
Hi, while this surely would be beneficial for application scenarios, this feature is nothing that we would consider implementing, as it can be done with separate volumes, would require significant work and weaken the volume abstraction. You can devise some semi-automated approach to managing different volumes similarly instead of having folders mounted within a volume. That being said, standard `mount` does not seem to support this feature either, but can simulate it with `--bind`. So you can mount the entire volume somewhere, and remount subtrees of it somewhere else if that helps you.
