### ISSUE TITLE
If the project is not died, please, make a new release

### ISSUE THREAD

**Issue by vitlav** [xtreemfs/xtreemfs#488]
The project exists without new release for long time (about two years). What about new release with openssl 1.1 support?

**Comment by robert-schmidtke** [comment]
Hi,

the latest unsable release (which is basically a patch release of the stable version, so nothing to worry about) supports openssl 1.1 (e.g. the Ubuntu 18.04 package is built against openssl 1.1.0g): http://download.opensuse.org/repositories/home:/xtreemfs:/unstable/ We are currently having some issues with our build server, which require some time fixing, and due to limited time available on our side (XtreemFS is a research project, after all), we currently only do somewhat irregular unstable releases. Thanks for your understanding.

Cheers
Robert

**Comment by ReinforcedPanda** [comment]
@vitlav xtreemfs isn't really supported anymore. The developers formed a new company and it is now a paid product.

https://www.quobyte.com

**Comment by robert-schmidtke** [comment]
@ReinforcedPanda there is no active development, that is correct. However you're free to fork, build and use the software as you like, or use one of the prebuilt packages that I linked above. Also we answer every question on the mailing list, as well as any issues raised here on GitHub.

I would kindly ask you not to pronounce the project unsupported without proper investigation, thanks.

Cheers
Robert
